### ISSUE TITLE
Is there a way to pass in constructor parameters when using picocli-codegen tool?

### ISSUE THREAD

**Issue by hanzo2001** [remkop/picocli#930]
I have been trying to adapt the example described in [https://picocli.info/picocli-on-graalvm.html](https://picocli.info/picocli-on-graalvm.html).

My case is more complex at the moment (I am using kotlin). However, just for testing I adapted the `picocli.codegen.aot.graalvm.Example` class by adding a single constructor parameter of type string as follows.

```java
@Command(/*...*/)
public class Example implements Runnable {
    /* ... */
    String needy = "needs";
    public Example(String need) {
        needy += " "+need;
    }
    public static void main(String[] args) {new CommandLine(new Example("a test")).execute(args);}
}
```

Now,  when I run the example

`java -cp alltheclasspaths p.c.a.g.ReflectionConfigGenerator p.c.a.g.Example`

I get the following error:

```
picocli.CommandLine$InitializationException: Could not inject spec
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:9941)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedFields(CommandLine.java:9886)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:9819)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5263)
	at picocli.CommandLine.<init>(CommandLine.java:223)
	at picocli.CommandLine.<init>(CommandLine.java:196)
	at picocli.codegen.aot.graalvm.ReflectionConfigGenerator$App.call(ReflectionConfigGenerator.java:99)
	at picocli.codegen.aot.graalvm.ReflectionConfigGenerator$App.call(ReflectionConfigGenerator.java:80)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1782)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2149)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2143)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2107)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1974)
	at picocli.CommandLine.execute(CommandLine.java:1903)
	at picocli.codegen.aot.graalvm.ReflectionConfigGenerator.main(ReflectionConfigGenerator.java:112)
Caused by: picocli.CommandLine$PicocliException: Could not get scope for field picocli.CommandLine$Model$CommandSpec picocli.codegen.aot.graalvm.Example.spec
	at picocli.CommandLine$Model$FieldBinding.set(CommandLine.java:10064)
	... 16 more
Caused by: picocli.CommandLine$InitializationException: Cannot instantiate picocli.codegen.aot.graalvm.Example: the class has no constructor
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4880)
	at picocli.CommandLine$Model$CommandUserObject.getInstance(CommandLine.java:10212)
	at picocli.CommandLine$Model$CommandUserObject.get(CommandLine.java:10232)
	at picocli.CommandLine$Model$FieldBinding.set(CommandLine.java:10063)
	... 16 more
Caused by: java.lang.NoSuchMethodException: picocli.codegen.aot.graalvm.Example.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3350)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2554)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4855)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4878)
	... 19 more
```

which is to be expected if I am not mistaken.

Is there a way to pass in the expected parameters to the constructor when using the `picocli-codegen` tool?

I'll ask about Kotlin in a separate issue (different error message, totally different animal)

**Comment by remkop** [comment]
This will require a change to the `ReflectionConfigGenerator` class to allow users to specify a custom factory. When that is done, you should be able to generate the reflect-config.json file with a command like this:

```
java -cp (...) p.c.a.g.ReflectionConfigGenerator --factory my.pkg.MyFactory my.pkg.Example
```

This factory then becomes responsible for creating the `Example` instance when the `my.pkgExample` class name is passed to `ReflectionConfigGenerator` on the command line.

Your factory can pass any data to the `Example` constructor, but it is up to the factory to get the constructor parameters from somewhere (either hard-coded, or read from a file, or taken from system properties, or some other way).

The factory should implement the [`picocli.CommandLine.IFactory`](https://picocli.info/#_custom_factory) interface.  Example factory implementation:

```java
import picocli.CommandLine;
import picocli.CommandLine.IFactory;

public class MyFactory implements IFactory {
    IFactory fallback = CommandLine.defaultFactory();

    @Override
    public <K> K create(Class<K> cls) throws Exception {
        if (cls == Example.class) {
            return (K) new Example("a test");
        }
        return fallback.create(cls);
    }
}
```

You can test your factory by changing your Example's main method to this:

```java
public static void main(String[] args) {
    new CommandLine(Example.class, new MyFactory()).execute(args);
}
```

**Comment by remkop** [comment]
@hanzo2001 I pushed a first version to master. Can you give this a try?

**Comment by hanzo2001** [comment]
Thank you for taking a look at this. I'll have some time in the evening to test it. I'll get back to you in a few hours

**Comment by remkop** [comment]
I added a test and I believe this should meet your needs.

You can test by checking out the latest master and building with:

```
gradlew clean publishToMavenLocal
```

That should publish `picocli-4.2.0-SNAPSHOT` to your local .m2 Maven cache. You can then try this in a project that uses the `info.picocli:picocli:4.2.0-SNAPSHOT` dependency.

Feedback welcome!

**Comment by hanzo2001** [comment]
I'll have to take your word and testing for it on Java. I have tried with Kotlin and I still get the error I described at #931 . This is mainly due to the fact that there seems to be an issue with the TypeCheck (`is`) I'm performing in the factory

##### MyCommandFactory.kt
```kotlin
package mypack
import picocli.CommandLine.defaultFactory
import picocli.CommandLine.IFactory
class MyCommandFactory: IFactory {
    override fun <K : Any?> create(cls: Class<K>?): K {
        println(cls)
        if (cls != null) {
            println("is cls an Example?")
            if ((cls as Any) is Example) {
                println("Give away rabbit!")
                return Example(InLoad::class.java, OutLoad::class.java) as K
            } else {
                println("NO")
            }
        }
        return defaultFactory().create(cls)
    }
}
```
##### The execution output
```
class mypack.Example
is cls an Example?
NO
picocli.CommandLine$InitializationException: Cannot instantiate mypack.Example: the class has no constructor
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4881)
	at picocli.CommandLine$Model$CommandUserObject.getInstance(CommandLine.java:10223)
	at picocli.CommandLine$Model$CommandSpec.userObject(CommandLine.java:5313)
	at picocli.CommandLine$Interpreter.clear(CommandLine.java:11341)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:11371)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:11277)
	at picocli.CommandLine.parseArgs(CommandLine.java:1311)
	at picocli.CommandLine.execute(CommandLine.java:1903)
	at mypack.Example.main(Example.kt:47)
Caused by: java.lang.NoSuchMethodException: mypack.Example.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4856)
	at mypack.MyCommandFactory.create(MyCommandFactory.kt:20)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4879)
	... 8 more
```
There has to be something I am doing wrong on my side. Kotlin's `instanceof` operator is `is` but for some reason
```kotlin
if ((cls as Any) is Example) ...
```
evaluates to false. The cast to `Any` is also required (for compilation) but I do not understand why.
The output is very indicative of something else entirely on my part.
```
println(cls)                  -> class mypack.Example
println("is cls an Example?") -> is cls an Example? (evaluates to false)
println("NO")                 -> NO
```
If I remove the check and simply return the Factory result, it all works out fine (the codegen and main).

I believe that this issue is closed thanks to your feature.

#931 is where I'll be stuck. There are still some corners of Kotlin that I am completely oblivious it seems

**Comment by remkop** [comment]
I think the problem is that the factory gets passed a `Class`, not an instance. The kotlin `is` operator is for instances, so that won't work. This worked for me: `cls == Example::class.java`. 

I added a full example to https://github.com/remkop/picocli/issues/931 .

I will close this issue and if there are any remaining issues let's continue discussion on #931.

**Comment by remkop** [comment]
@hanzo2001, All,

[picocli 4.2.0](https://github.com/remkop/picocli/releases/tag/v4.2.0) has been released, including this fix. Enjoy!
